---
extends:
  - next/core-web-vitals
  - plugin:import/recommended
  - plugin:import/typescript

plugins:
  - import

parser: '@typescript-eslint/parser'

settings:
  project: ./tsconfig.json
  import/resolver:
    typescript: true
    node: true

rules:
  react/display-name: off
  import/no-unresolved: error
  import/order:
    - error
    - newlines-between: always
      pathGroups:
        - pattern: '@project-management-app/**'
          group: internal
          position: before
      groups:
        - builtin
        - external
        - - internal
          - parent
          - sibling
          - index
