import {
  RiDeleteBinLine,
  RiGlobalLine,
  RiArrowDropDownLine,
  RiGithubFill,
  RiAddLine,
  RiLinkedinFill,
  RiEdit2Line,
  RiCloseLine,
  RiInformationLine,
  RiMenuLine,
  RiLink,
  RiCheckLine,
  RiSearchLine,
  RiCloseCircleFill,
  RiStickyNoteFill,
  RiArtboardFill,
  RiBrushLine,
  RiSettings4Line,
  RiEyeLine,
  RiEyeOffLine,
  RiArrowDownSLine,
} from 'react-icons/ri';

import { RsSchoolLogo } from './components/components';

const Icon = {
  BinLine: RiDeleteBinLine,
  GlobalLine: RiGlobalLine,
  ArrowDropDownLine: RiArrowDropDownLine,
  GithubFill: RiGithubFill,
  AddLine: RiAddLine,
  LinkedinFill: RiLinkedinFill,
  EditLine: RiEdit2Line,
  CloseLine: RiCloseLine,
  InformationLine: RiInformationLine,
  MenuLine: RiMenuLine,
  LinkLine: RiLink,
  CheckLine: RiCheckLine,
  SearchLine: RiSearchLine,
  CloseCircleFill: RiCloseCircleFill,
  StickyNoteFill: RiStickyNoteFill,
  ArtboardFill: RiArtboardFill,
  BrushLine: RiBrushLine,
  SettingsLine: RiSettings4Line,
  EyeLine: RiEyeLine,
  EyeOffLine: RiEyeOffLine,
  ArrowDownSLine: RiArrowDownSLine,
  RsSchoolLogo,
} as const;

export { Icon };
